AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - spec/gruf/**/*
    - spec/**/*_pb.rb
    - .bundle/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
require:
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-packaging

# Allow *VALID_CONFIG_KEYS.keys
Lint/AmbiguousOperator:
  Enabled: false

# This cop conflicts with other cops
Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 40

# Exclude gRPC method names in demo
Naming/AccessorMethodName:
  Exclude:
    - spec/demo/**/*
