AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - spec/gruf/**/*
    - spec/**/*_pb.rb
    - .bundle/**/*
    - vendor/**/*
    - tmp/**/*
    - log/**/*
plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

# Allow *VALID_CONFIG_KEYS.keys
Lint/AmbiguousOperator:
  Enabled: false

# This cop conflicts with other cops
Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 40

# Exclude gRPC method names in demo
Naming/AccessorMethodName:
  Exclude:
    - spec/demo/**/*

Style/RedundantConstantBase:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false
