# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/ThingService.proto

require 'google/protobuf'


descriptor_data = "\n\x16rpc/ThingService.proto\x12\x03rpc\"!\n\x05Thing\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\",\n\x0fGetThingRequest\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05sleep\x18\x02 \x01(\r\"-\n\x10GetThingResponse\x12\x19\n\x05thing\x18\x01 \x01(\x0b\x32\n.rpc.Thing2I\n\x0cThingService\x12\x39\n\x08GetThing\x12\x14.rpc.GetThingRequest\x1a\x15.rpc.GetThingResponse\"\x00\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Rpc
  Thing = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.Thing").msgclass
  GetThingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetThingRequest").msgclass
  GetThingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetThingResponse").msgclass
end
