#!/usr/bin/env ruby
# frozen_string_literal: true

# Copyright (c) 2019-present, BigCommerce Pty. Ltd. All rights reserved
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
$LOAD_PATH.unshift File.expand_path('../../lib', __dir__)
require 'gruf/prometheus'
require_relative 'thing_controller'
require_relative '../support/custom_type_collector'
require_relative '../support/custom_collector'
require 'logger'
ENV['PROCESS'] = 'demo'

logger = ::Logger.new($stdout)
logger.level = ::Logger::Severity::DEBUG

::Bigcommerce::Prometheus.configure do |c|
  c.server_port = 8_622
  c.server_host = '0.0.0.0'
  c.logger = logger
end

::Gruf.configure do |c|
  c.logger = logger
  c.grpc_logger = logger
  c.server_binding_url = '0.0.0.0:8621'
  c.hooks.use(
    Gruf::Prometheus::Hook,
    type_collectors: [CustomTypeCollector.new]
  )
end

client = Gruf::Client.new(service: ::Rpc::ThingService, options: { hostname: '0.0.0.0:8621' })
resp = client.call(:GetThing)

logger.info resp.message
